### ISSUE TITLE
Choose Queue

### ISSUE THREAD

**Issue by awm33** [cognoma/task-service#4]
I'd like to nail down what queue will be used initially. An abstraction layer will be used to make it so other "queue backends" can implemented.

The following pseudocode functions must be able to be implemented on top of the queue:
- createQueue(queueName)
- destroyQueue(queueName)
- getMessage(queueName, numberOfMessages)
  - Returns result with receive handle if message ID can't be used for touch and release.
  - numberOfMessages  - optional requirement - Could potentially just call this function multiple times.
- putMessage(queueName, task)
  - Returns message ID
- deleteMessage(queueName, task)
  - Sometimes this is also called acknowledgement. Basically, the task is completed or failed.
- touchMessage(queueName, task, newTimeout)
  - Uses the message id or receipt handle to update the timeout on the message.
- releaseMessage(queueName, task)
  - Releases the message back to the queue for retrieving by another worker. Usually this is implemented by calling touchMessage with a timeout of 0.

These are the functions the abstraction class would implement.

I've developed task queues against SQS and Google Pub/Sub. I have the most experience with SQS. For the local development environment, there are solutions for running something that mimics the APIs for SQS and Google Pub/Sub. There are also production ready open source solutions compatible with the SQS API.

I would recommend a cloud service such as SQS or Google Pub/Sub over a self hosted solution. One less thing to manage.

Redis is another contender and possibly RabbitMQ, though I would need to test that.

**Comment by awm33** [comment]
@cgreene Do we know what cloud we are using? I mentioned the abstraction we discussed before. I think that would be a great way to keep this super flexible for the future.

**Comment by cgreene** [comment]
I am supportive of a solution that you prefer as long as it is portable between cloud vendors. Happy to use one that is provided by the vendor (e.g. SQS on AWS) as long as we could also run that queue at a production level in a container on another vendor.

At the moment I would plan to start out on Google. They have been supportive of hackathons in the past and are a bit easier to coordinate with than other providers for support. It sounds like pub/sub would be ideal, as long as we can have relatively loose coupling to it. Thanks!

**Comment by awm33** [comment]
@cgreene Sounds good!
